# Generated by Django 2.0.1 on 2018-01-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180109_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postblog',
            options={'ordering': ['-timestamp', '-update']},
        ),
        migrations.AddField(
            model_name='postblog',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
